### ISSUE TITLE
[task]Inicio de sesion con una API falsa (No estan necesario aun, pero podriamos adelantar)

### ISSUE THREAD

**Issue by gmsanchezgaray** [pgPilfs/pil-money-g4b-grupo4b#44]

**Comment by JoaquinGomez1** [comment]
Que sería una API 'Falsa', tener una ruta para hacerle la petición http desde el front sin tener que guardar nada en la base de datos?
Porque si la idea es que se haga una petición http se podría hacer con un mock en un archivo json directamente desde el front para después poder integrarlo mas fácil con el back

**Comment by JoaquinGomez1** [comment]
Ahí encontré un recurso para hacer API falsas que nos vendría bien para ir simulando las peticiones http y de paso se nos hace mas fácil después hacer la integración con el backend.
La herramienta se llama [Mockoon](https://mockoon.com/) y hace muy accesible el tema de hacer Mock de API's porque te arma un servidor local en el que podés hacer todo tipo de peticiones a un servidor real que corre dentro de tu máquina
